name: Continuous Build

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  TARGET_NODE_VERSION: '14.17.1'

jobs:
  documentation:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/mlc_config.json

  lint-build-publish:
    name: Lint, build, validate, test, publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Validate
        run: yarn validate
      - name: Test
        run: yarn test
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Export S3 Payloads
        run: yarn export-ops-json-payloads
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload JSON Payloads with commit hash to S3
        run: aws s3 cp json-exports s3://operations-development/${{ github.sha }} --acl public-read --recursive
      - name: Upload JSON Payloads as latest to S3
        run: aws s3 cp json-exports s3://operations-development/latest --acl public-read --recursive